In [1]:
import numpy as np

## Numpy arrays
- Tek boyutlu ya da iki boyutlu diziler oluşturabiliyoruz

In [2]:
Liste = [2,4,8,9]

In [3]:
type(Liste)

list

In [5]:
np.array(Liste) # bu şekilde yazıp numpy arrayine çevirebiliyoruz.

array([2, 4, 8, 9])

In [6]:
type(np.array(Liste))

numpy.ndarray

In [7]:
# dizi içinde dizi, liste içinde liste 

In [12]:
matrixListesi = [[3,65,4],[45,778,34],[3,8,96]]

In [13]:
matrixListesi

[[3, 65, 4], [45, 778, 34], [3, 8, 96]]

In [15]:
np.array(matrixListesi) # satır kolon referansları verebiliyoruz bu yüzden marix gösterimi önemli

array([[  3,  65,   4],
       [ 45, 778,  34],
       [  3,   8,  96]])

In [5]:
import numpy as np
deneme = [[3,5],[4,8]]

In [6]:
np.array(deneme)

array([[3, 5],
       [4, 8]])

## Arange Methodu


In [17]:
np.arange(0,10) # range metodu da bu işlevi görüyordu, dizilerde. Arange artık bir liste değil direk bir numpy array oluşturuyor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(2,20,4) # arange'in step size ile kullanımı 

array([ 2,  6, 10, 14, 18])

## Zeros

In [7]:
np.zeros(5) # içinde 0 olan dizi yaratmak için zeros kullanabiliriz.

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,2)) # dizi içinde dizi olduğundan çift parantezle yazdık, (tuple gibi verdik 2,2)

array([[0., 0.],
       [0., 0.]])

## Ones

In [26]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Linspace
- Belittiğimiz numaralar arasında eşit olarak boyutlandırılmış, eşit aralık bırakılmış bir dizi oluşturuyor.

In [8]:
np.linspace(0,20,5) # eşit mesafeli 5 aralık bıraktı

array([ 0.,  5., 10., 15., 20.])

In [32]:
np.linspace(0,10,20) # aralarında eşit fark var / stopping index yok sonuncu indexi de dahil eder.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Eye 
- Identity Matrix

In [34]:
np.eye(5) # Köşegen matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random
- numpy'ın kendi random'ı

In [10]:
np.random.randn(4) # randn, numpy dizisi döndürmemizi sağlıyor burda

array([ 0.68614293, -1.0243802 , -0.18248159, -0.27800863])

In [9]:
np.random.rand(2,2)

array([[0.72244934, 0.74081084],
       [0.67179937, 0.42640171]])

In [41]:
np.random.randint(4,67) # Tek değer döndürmek istersek / direk int döndürür / Son verdiğin rakamı baz almaz

65

In [44]:
np.random.randint(1,10,5) # 1 ve 10 arasında 10 dahil olmamak üzere 5 tane rastgele rakam getir dedik.

array([7, 8, 2, 5, 3])

In [45]:
np.random.randint(1,300,5)

array([198, 285,  74, 196,  69])

In [46]:
# Bu değerleri bir değişkene eşitliyebiliriz

In [13]:
NumpyDizim = np.arange(30)

In [14]:
NumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
RandomDizim = np.random.randint(3,66,4)

In [16]:
RandomDizim

array([27, 58,  7, 63])

In [17]:
type(RandomDizim)

numpy.ndarray

## Numpy Dizi Methodları

In [18]:
NumpyDizim.reshape(5,6) # Row ve Column oluşuturduk 30 sayıyı, matrix formatına getirdi reshape / verimizi bu şekilde istediğimiz
# şekle sokabiliyoruz

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [54]:
NumpyDizim.max()

29

In [56]:
RandomDizim.max()

43

In [57]:
RandomDizim.min()

8

In [19]:
RandomDizim.argmax() # arrayım'ın max değerinin indexini veriyor.

3

In [61]:
RandomDizim.argmin()

2

In [63]:
NumpyDizim.shape # shape' e fonk koymuyoruz bu direk bir özellik çünkü

(30,)

In [65]:
reshapeDizim = NumpyDizim.reshape(5,6)

In [66]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## Numpy Operasyonlar

In [21]:
import numpy as np

In [22]:
Dizim = np.arange(0,15)

In [23]:
Dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
# Bu dizi içinden 5. indexi nasıl alırız
Dizim[5]
# listeler ile aynı özellikte buraya kadar, index ile çağırabiliyoruz

5

In [25]:
Dizim[3:7] # Listelerle aynı çalışıyor

array([3, 4, 5, 6])

In [26]:
Dizim[3:8] = -5 

In [27]:
Dizim # Kendi dizimdeki elemanları bu şekilde değiştirdim.

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [86]:
baskaDizi = np.arange(0,24)

In [87]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [88]:
slicingDizisi = baskaDizi[4:9] 

In [89]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [90]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [91]:
slicingDizisi[:]

array([4, 5, 6, 7, 8])

In [92]:
slicingDizisi[:] = 700 # dersek tek tek tüm elemanlarını 700 e eşitlemesi gerektiğini anlıyor

In [93]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [94]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [95]:
# Fakat o da ne baskaDizi deki rakamlarda değişti.
# Numpy dizilerinde böyle bir durum var bir parçayı alıyorsunuz diziden değiştiriyosunuz ve bu asıl diziye yansıyor

# orjinalini korumak istiyorsak ; 

In [97]:
ornekDizi = np.arange(0,24)

In [98]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [101]:
ornekDiziKopyası = ornekDizi.copy() # Kopyasını oluşturduk

In [102]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [103]:
ornekDiziKopyasıSlicing = ornekDiziKopyası[5:8]

In [104]:
ornekDiziKopyasıSlicing[:] = 800

In [105]:
ornekDiziKopyasıSlicing

array([800, 800, 800])

In [106]:
ornekDiziKopyası

array([  0,   1,   2,   3,   4, 800, 800, 800,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [108]:
ornekDizi # Orjinal dizim değişmedi böylece

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 2 Boyutlu Diziler / Matrixler

In [109]:
benimListem = [3,4,5],[6,7,8],[5,7,4]

In [111]:
matrixDizim = np.array(benimListem)

In [112]:
matrixDizim

array([[3, 4, 5],
       [6, 7, 8],
       [5, 7, 4]])

In [113]:
matrixDizim[0]

array([3, 4, 5])

In [116]:
matrixDizim[1][2] 

8

In [117]:
matrixDizim[1,2]  # Aynı şeyler

8

In [118]:
# Slicing yapalım 

In [119]:
matrixDizim[1:,2]

array([8, 4])

In [120]:
matrixDizim[0:2]

array([[3, 4, 5],
       [6, 7, 8]])

In [121]:
matrixDizim[2:,2:]

array([[4]])

In [122]:
yeniList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [127]:
yeniMatrix = np.array(yeniList)

In [128]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [130]:
yeniMatrix[[0,2,4]] # 0,2 ve 4. indexleri liste olarak verdim bana istediiğimi getirdi. / Fency Index

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operasyonlar

In [134]:
yeniDizi = np.random.randint(1,100,20)

In [135]:
yeniDizi

array([ 8, 65, 67, 21, 35, 50, 36, 80, 54, 10, 36, 31, 75, 45, 37,  3, 89,
       14, 99, 77])

In [138]:
yeniDizi < 24 

array([ True, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False,  True,
       False, False])

In [139]:
sonucDizisi = yeniDizi > 24

In [140]:
sonucDizisi

array([False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [141]:
yeniDizi

array([ 8, 65, 67, 21, 35, 50, 36, 80, 54, 10, 36, 31, 75, 45, 37,  3, 89,
       14, 99, 77])

In [143]:
yeniDizi[sonucDizisi] # sadece true'ları getirir

array([65, 67, 35, 50, 36, 80, 54, 36, 31, 75, 45, 37, 89, 99, 77])

In [145]:
yeniDizi[yeniDizi > 24] # Tek satırdaki filtreleme işlemi ise bu şekilde

array([65, 67, 35, 50, 36, 80, 54, 36, 31, 75, 45, 37, 89, 99, 77])

In [146]:
sondizi = np.arange(0,24)

In [149]:
sondizi + sondizi # direk topluyor

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [150]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [151]:
sondizi - sondizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [152]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [153]:
np.max(sondizi)

23

In [154]:
np.min(sondizi)

0